
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS users;
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, username VARCHAR (32), email VARCHAR (32), password VARCHAR(100));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
